name: "Test Action"
description: "Test Action Inputs"
inputs:
  NUMBER_A:
    required: false
    type: number
    default: 7
  CHOICE_A:
    required: false
    type: choice
    options: ["herp","derp"]
    default: "blah"
  BOOLEAN_A:
    required: false
    type: boolean
    default: false
  STRING_A:
    required: false
    type: string
    default: ""
  HERP:
    required: false
    type: boolean
  DERP:
    required: false
    type: boolean

runs:
  using: "composite"
  steps:
  
    - name: "echo variables"
      shell: bash
      run: |
        set -x
        echo "${{ inputs.NUMBER_A }}"
        echo ${{ inputs.CHOICE_A }}
        echo ${{ inputs.BOOLEAN_A }}
        echo ${{ inputs.STRING_A }}
    - name: "only run if string input is true"
      shell: bash
      if: ${{ inputs.STRING_A }}
      run: |
        echo "string evaluated to true"
        echo "${{ inputs.STRING_A }}"
    - name: "only run if string input is false"
      shell: bash
      if: ${{ !inputs.STRING_A }}
      run: |
        echo "string evaluated to false"
        echo "${{ inputs.STRING_A }}"
