name: "Test Action"
description: "Test Action Inputs"
inputs:
  NUMBER_A:
    required: false
    type: number
    default: 7
  CHOICE_A:
    required: false
    type: choice
    options: ["herp","derp"]
    default: "blah"
  BOOLEAN_A:
    required: false
    type: boolean
    default: false
  STRING_A:
    required: false
    type: string
    default: ""
  YES:
    required: false
    type: boolean
    default: "YES"
  NO:
    required: false
    type: boolean
    default: "NO"
  TRUE:
    required: false
    type: boolean
    default: "TRUE"

runs:
  using: "composite" 
  steps:    
    - name: Test A
      shell: bash
      run: |
        TEST="blah
        derp
        herp"
        echo "ASSETS=$TEST" >> "$GITHUB_ENV"

    - name: Test B
      shell: bash
      run: |
        echo $ASSETS
