name: test
on:
  workflow_dispatch:
    inputs:
      NUMBER:
        required: false
        type: number
        default: 9
      CHOICE:
        required: false
        type: choice
        options: ["herp","derp"]
        default: "derp"
      BOOLEAN:
        required: false
        type: boolean
        default: true
      STRING:
        required: false
        type: string
        default: "oh dear"

jobs:

  test:
    name: "Show input output"
    runs-on: ubuntu-latest

    steps:

      - name: "Checkout"
        run: |
          set -x
          echo "${{ inputs.NUMBER }}"
          echo ${{ inputs.CHOICE }}
          echo ${{ inputs.BOOLEAN }}
          echo ${{ inputs.STRING }}
