name: test
on:
  workflow_dispatch:
    inputs:
      NUMBER:
        required: false
        type: number
        default: 9
      CHOICE:
        required: false
        type: choice
        options: ["herp","derp"]
        default: "derp"
      BOOLEAN:
        required: false
        type: boolean
        default: true
      STRING:
        required: false
        type: string
        default: "oh dear"

jobs:

  test:
    name: "Show input output"
    runs-on: ubuntu-latest

    steps:

      - name: "Echo inputs"
        run: |
          set -x
          echo "${{ inputs.NUMBER }}"
          echo ${{ inputs.CHOICE }}
          echo ${{ inputs.BOOLEAN }}
          echo ${{ inputs.STRING }}
      - name: "Check out this repository"
        uses: actions/checkout@v4
      - name: "No inputs"
        uses: ./
      - name: "With inputs form workflow"
        uses: ./
        with:
          NUMBER_A: ${{ inputs.NUMBER }}
          CHOICE_A: ${{ inputs.CHOICE }}
          BOOLEAN_A: ${{ inputs.BOOLEAN }}
          STRING_A: ${{ inputs.STRING }}
